/**
 * The .txt twins must match the .md they mirror.
 *
 * Every prose doc in this repo carries a plain-text twin, because markdown
 * renders in only some of the places these files get read: GitHub shows raw
 * markup in diffs and review, and editors and pagers show it always.
 *
 * The twins used to be written by hand, and by the time this test arrived
 * they had already drifted from each other - em dashes turned to hyphens in
 * one file and not the next, list text re-wrapped in one twin and not its
 * source. None of it was caught, because the failure mode of a hand-kept
 * duplicate is that nobody reads both copies. The one person reading the
 * .txt has no way to know it disagrees with the .md.
 *
 * So the twins are generated by scripts/md-txt.mjs and this test runs its
 * --check: edit a .md, forget to regenerate, and the suite fails here rather
 * than shipping a mirror that quietly says something else.
 *
 * Line endings are normalised on both sides. The working tree is CRLF on
 * Windows (core.autocrlf) and LF in the repository and on CI, so a literal
 * comparison would pass or fail depending on which machine ran it - the
 * worst kind of check, since it would be green exactly where it was written.
 */
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { render, sources, stale, twinOf } from "../scripts/md-txt.mjs";

const REPO = join(fileURLToPath(new URL(".", import.meta.url)), "..", "..");

describe("the plain-text twins are generated, and in sync", () => {
  it("every twin matches its source", () => {
    // The message names the stale files, so a failure says what to fix.
    expect(stale()).toEqual([]);
  });

  it("finds the prose docs, and not prepack's copies of them", () => {
    const found = sources().map((s) => s.slice(REPO.length + 1).replace(/\\/g, "/"));
    expect(found).toContain("README.md");
    expect(found).toContain("PLAN.md");
    expect(found).toContain("SECURITY.md");
    expect(found).toContain("skill/SKILL.md");
    // prepack drops gitignored copies at server/README.md and server/skill/;
    // twinning a build artifact would only write files the next pack replaces.
    expect(found.some((f) => f.startsWith("server/"))).toBe(false);
  });

  it("keeps frontmatter byte for byte", () => {
    // The description is parsed by whatever loads the skill. Stripping a
    // backtick out of it would change the value a client reads, which is the
    // one transformation a plain-text mirror must never make.
    const out = render(["---", "name: x", "description: a `b` and **c**", "---", "", "# H", "text"].join("\n"));
    expect(out.split("\n").slice(0, 4)).toEqual(["---", "name: x", "description: a `b` and **c**", "---"]);
  });

  it("underlines headings, strips inline markup, and keeps link targets", () => {
    const out = render(["# Title", "", "## Section", "", "**bold** and `code` and [text](https://e.example)."].join("\n"));
    expect(out).toContain("Title\n=====");
    expect(out).toContain("Section\n-------");
    expect(out).toContain("bold and code and text (https://e.example).");
  });

  it("does not print a link target that is already the link text", () => {
    // The README links build-version.json to itself. Rendering that as
    // "build-version.json (build-version.json)" says nothing twice.
    expect(render("See [build-version.json](build-version.json).")).toContain("See build-version.json.");
    expect(render("See [the file](build-version.json).")).toContain("See the file (build-version.json).");
    // The README writes that self-link with inline-code markers, which come
    // off after the link is expanded - so the comparison has to ignore them.
    expect(render("See [`build-version.json`](build-version.json).")).toContain("See build-version.json.");
  });

  it("drops fence markers and indents the code inside", () => {
    const out = render(["Run it:", "", "```bash", "npm test", "```"].join("\n"));
    expect(out).toContain("    npm test");
    expect(out).not.toContain("```");
  });

  it("the skill twin still carries the description the client reads", async () => {
    // SKILL.md is both machine-loaded and prose, so it is twinned - and the
    // description is the part a client reads to decide the skill applies.
    const txt = await readFile(join(REPO, "skill", "SKILL.txt"), "utf8");
    const md = await readFile(join(REPO, "skill", "SKILL.md"), "utf8");
    const line = (s: string) => s.split(/\r?\n/).find((l) => l.startsWith("description:"));
    expect(line(txt)).toBe(line(md));
  });
});
